<a href="https://colab.research.google.com/github/aryanchaprana/aryanchaprana/blob/main/ML_16(RANDOM_SAMPLE_IMPUTER).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split
import seaborn as sns

In [3]:
df=pd.read_csv('/content/train.csv',usecols=['Age','Fare','Survived'])

In [4]:
df

     Survived   Age     Fare
0           0  22.0   7.2500
1           1  38.0  71.2833
2           1  26.0   7.9250
3           1  35.0  53.1000
4           0  35.0   8.0500
..        ...   ...      ...
886         0  27.0  13.0000
887         1  19.0  30.0000
888         0   NaN  23.4500
889         1  26.0  30.0000
890         0  32.0   7.7500

[891 rows x 3 columns]

In [12]:
df.isnull().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [10]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
X_train['Age_imputed']=X_train['Age'] #this adds new column in X_Train same as the age column
X_test['Age_imputed']=X_test['Age']

In [16]:
X_train

      Age      Fare  Age_imputed
331  45.5   28.5000         45.5
733  23.0   13.0000         23.0
382  32.0    7.9250         32.0
704  26.0    7.8542         26.0
813   6.0   31.2750          6.0
..    ...       ...          ...
106  21.0    7.6500         21.0
270   NaN   31.0000          NaN
860  41.0   14.1083         41.0
435  14.0  120.0000         14.0
102  21.0   77.2875         21.0

[712 rows x 3 columns]

In [17]:
X_train['Age_imputed'][X_train['Age_imputed'].isnull()] #is formula se hme jitni bhe null valyues h vo mil jaate hai

29    NaN
55    NaN
533   NaN
495   NaN
468   NaN
       ..
330   NaN
214   NaN
466   NaN
121   NaN
270   NaN
Name: Age_imputed, Length: 140, dtype: float64

In [18]:
X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values #this code gives us the random 140 values after dropping the null values

array([32.  , 18.  , 35.  , 14.  , 26.  , 48.  , 21.  , 28.  , 22.  ,
       21.  , 16.  , 34.  , 25.  , 56.  , 45.  , 16.  , 16.  , 36.  ,
       26.  , 50.  , 18.  , 39.  , 19.  , 58.  , 35.  , 39.  , 17.  ,
       20.  , 27.  , 20.  , 38.  , 40.  , 43.  , 61.  , 33.  , 33.  ,
        0.42, 54.  , 18.  , 39.  , 36.  , 21.  , 23.  , 29.  , 25.  ,
       18.  , 22.  , 23.  , 48.  , 22.  , 35.  , 37.  , 58.  , 18.  ,
       35.  , 14.  , 45.  , 29.  , 43.  , 50.  , 45.  , 47.  , 32.  ,
       28.  , 33.  , 40.5 , 15.  , 32.  , 30.  , 18.  , 21.  , 18.  ,
       21.  , 48.  , 48.  , 50.  , 30.  , 44.  , 34.  , 19.  , 27.  ,
       20.  ,  1.  , 27.  , 47.  , 19.  , 34.  , 18.  , 31.  , 41.  ,
        0.92, 59.  ,  3.  ,  0.75,  4.  , 23.  , 26.  , 28.  , 29.  ,
       38.  , 24.  , 46.  , 21.  ,  5.  , 33.  , 29.  , 27.  , 32.  ,
       25.  , 27.  , 18.  , 25.  , 27.  , 24.  , 27.  , 26.  , 21.  ,
        4.  , 18.  , 24.  , 32.  , 42.  , 17.  , 18.  , 31.  , 51.  ,
       32.  , 21.  , 31.  , 40.5 , 36.  , 20.  ,  9.  , 39.  , 22.  ,
       28.  , 35.  , 56.  , 38.  ,  3.  ])

In [19]:
X_train['Age_imputed'][X_train['Age_imputed'].isnull()]=X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values

<ipython-input-19-5ab996833007>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_train['Age_imputed'][X_train['Age_imputed'].isnull()]=X_train['Age'].dropna().sample(X_train['Age'].isnull().sum()).values

In [ ]:
#sampled_value=X_train['Age'].dropna().sample(1,random_state=int(observation['Fare']))---is code use karne se the predictions will not be rnadom

now with categorical data

In [20]:
data=pd.read_csv('/content/house-train.csv',usecols=['GarageQual','FireplaceQu','SalePrice'])

In [21]:
data.isnull().mean()*100

FireplaceQu    47.260274
GarageQual      5.547945
SalePrice       0.000000
dtype: float64

In [22]:
X=data
y=data['SalePrice']

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [24]:
X_train['G_imput']=X_train['GarageQual']
X_test['G_imput']=X_test['GarageQual']
X_train['Fire_impute']=X_train['FireplaceQu']
X_test['Fire_impute']=X_test['FireplaceQu']

In [25]:
X_train

     FireplaceQu GarageQual  SalePrice G_imput Fire_impute
254          NaN         TA     145000      TA         NaN
1066          TA         TA     178000      TA          TA
638          NaN        NaN      85000     NaN         NaN
799           TA         TA     175000      TA          TA
380           Gd         TA     127000      TA          Gd
...          ...        ...        ...     ...         ...
1095          Gd         TA     176432      TA          Gd
1130          TA         TA     135000      TA          TA
1294         NaN         TA     115000      TA         NaN
860           Gd         TA     189950      TA          Gd
1126          TA         TA     174000      TA          TA

[1168 rows x 5 columns]

In [26]:
X_train['G_imput'][X_train['G_imput'].isnull()]=X_train['GarageQual'].dropna().sample(X_train['GarageQual'].isnull().sum()).values
X_test['G_imput'][X_test['G_imput'].isnull()]=X_test['GarageQual'].dropna().sample(X_test['GarageQual'].isnull().sum()).values
X_train['Fire_impute'][X_train['Fire_impute'].isnull()]=X_train['FireplaceQu'].dropna().sample(X_train['FireplaceQu'].isnull().sum()).values
X_test['Fire_impute'][X_test['Fire_impute'].isnull()]=X_test['FireplaceQu'].dropna().sample(X_test['FireplaceQu'].isnull().sum()).values

<ipython-input-26-9e663b942280>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_train['G_imput'][X_train['G_imput'].isnull()]=X_train['GarageQual'].dropna().sample(X_train['GarageQual'].isnull().sum()).values
<ipython-input-26-9e663b942280>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['G_imput'][X_train['G_imput'].isnull()]=X_train['GarageQual'].dropna().sample(X_train['GarageQual'].isnull().sum()).values
<ipython-input-26-9e663b942280>:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_test['G_imput'][X_test['G_imput'].isnull()]=X_test['GarageQual'].dropna().sample(X_test['GarageQual'].isnull().sum()).values
<ipython-input-26-9e663b942280>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['G_imput'][X_test['G_imput'].isnull()]=X_test['GarageQual'].dropna().sample(X_test['GarageQual'].isnull().sum()).values
<ipython-input-26-9e663b942280>:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_train['Fire_impute'][X_train['Fire_impute'].isnull()]=X_train['FireplaceQu'].dropna().sample(X_train['FireplaceQu'].isnull().sum()).values
<ipython-input-26-9e663b942280>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Fire_impute'][X_train['Fire_impute'].isnull()]=X_train['FireplaceQu'].dropna().sample(X_train['FireplaceQu'].isnull().sum()).values
<ipython-input-26-9e663b942280>:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  X_test['Fire_impute'][X_test['Fire_impute'].isnull()]=X_test['FireplaceQu'].dropna().sample(X_test['FireplaceQu'].isnull().sum()).values
<ipython-input-26-9e663b942280>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['Fire_impute'][X_test['Fire_impute'].isnull()]=X_test['FireplaceQu'].dropna().sample(X_test['FireplaceQu'].isnull().sum()).values

In [27]:
X_train

     FireplaceQu GarageQual  SalePrice G_imput Fire_impute
254          NaN         TA     145000      TA          TA
1066          TA         TA     178000      TA          TA
638          NaN        NaN      85000      TA          Gd
799           TA         TA     175000      TA          TA
380           Gd         TA     127000      TA          Gd
...          ...        ...        ...     ...         ...
1095          Gd         TA     176432      TA          Gd
1130          TA         TA     135000      TA          TA
1294         NaN         TA     115000      TA          Gd
860           Gd         TA     189950      TA          Gd
1126          TA         TA     174000      TA          TA

[1168 rows x 5 columns]

In [ ]:
from sklearn.impute import SimpleImputer